### PR TITLE
Minor Improvements to enforce PEP8 Standards and remove deprecated calls

### PR DESCRIPTION
**Pull request by scorpionhiccup**

### CODE REVIEW

**Comment by buffer** [comment]
Thanks for the pull request. By the way you patched androguard and peepdf which are external projects which are maintained in the source tree just for keeping the Thug users life easier while installing. This means the next time I will sync such repos your changes will be lost unfortunately. Could you please resubmit the pull request submitting just the changes to the Thug code? Thanks for your contribution!

**Comment by sharvilkatariya** [comment]
Yep, merged the changes now.    
Can you explain the role of Zope Interface? Is the role of meta-class the only answer?

**Comment by buffer** [comment]
Zope interface is used in order to validate the interfaces exposed by a third party plugin in order to be sure they are compliant with what defined in IThugPlugin.py

**Comment by sharvilkatariya** [comment]
But aren't you looping through all the options(from getopt) and then checking for just option[0] to be a valid option? I don't understand why the patch is wrong.

**Comment by buffer** [comment]
Oops! You are absolutely right. Never evaluate a patch while being sick. Please feel free to reopen the pull request and I will integrate it.

**Comment by sharvilkatariya** [comment]
Hey, no problem. Even I had to rethink to understand...   
Cheers

**Pull request merged**
