### PR TITLE
Update usage documentation

### PR DESCRIPTION
**Pull request by joshlarsen**
Found a few discrepancies when looking through the usage docs.

### CODE REVIEW

**Comment by buffer** [comment]
It seems like you're using a very old version of Thug because the usage documentation is updated with the currently supported features (see [1] and [2])

[1] https://github.com/buffer/thug/blob/master/thug/thug.py#L40
[2] https://github.com/buffer/thug/blob/master/docs/source/usage.rst

**Comment by joshlarsen** [comment]
You're right, I should have noticed that. However, I am using the Docker image - which apparently contains version `0.6.7`.

**Comment by buffer** [comment]
Can you please try with this docker image https://hub.docker.com/r/buffer/thug/? It seems like the one reported in the documentation is not up to date. Thanks!

**Comment by joshlarsen** [comment]
```
$ thug -V
Thug 0.9.39
```

```
REPOSITORY              TAG            IMAGE ID            CREATED             SIZE
buffer/thug             latest         041d150affeb        3 months ago        802MB
honeynet/thug           latest         747c09b4052a        3 years ago         604MB
```

**Comment by buffer** [comment]
Rebuilding the image right now. In a few minutes v0.9.46 should be available.

**Pull request closed without merging**
