### PR TITLE
Amazon Web Information Service addition

### PR DESCRIPTION
**Pull request by tomdaq**
Not anywhere near complete but there's some code that might be usable.

Uses myawis to setup the connection: https://github.com/ashim888/awis

### CODE REVIEW

**Comment by buffer** [comment]
Taking a look at myawis code it seems like it makes use of some package versions which conflict with the ones currently used by Thug. Thinking to slightly adapt myawis codebase and embedding in the Thug tree could be the best way to go. I'll let you know in the next days.

**Comment by kira0204** [comment]
Hi, I would like to know the status of this, thanks.

**Comment by buffer** [comment]
My idea was about merging this PR in a different branch and working on that. I would like to have AWIS basic support in Thug so not to be forced to use different package versions.

**Comment by kira0204** [comment]
Let's move forward with merging this PR in another branch, we can then check out the discrepancy in the package versions and make it compatible with thug.

**Pull request merged**
