### PR TITLE
Add support for WScriptNetwork object.

### PR DESCRIPTION
**Pull request by tweemeterjop**
Adds support for the WScriptNetwork object which was used in some recent samples.

Ideally the attributes shouldn't be static but retrieved using WScriptShell.ExpandEnvironmentStrings(). Any comments on how to do that?

Also did some improvements on the Scripting.FileSystemObject module.

### CODE REVIEW

**Comment by buffer** [comment]
Thanks for the patch! Just a quick question before merging. Do you think it could be worth randomizing the names returned by EnumPrinterConnections and EnumNetworkDrives in order to avoid Thug to be detected?

**Comment by tweemeterjop** [comment]
Randomizing those enums is an option yes however i've only seen samples that look at the length of the returned object.

**Comment by buffer** [comment]
@pdelsante built a really effective mechanism which works by defining the template variable in the json personalities files. I think we could just use the same mechanism for this purpose thus preventing any possibility to be detected now and in the next future. Thoughts?

**Comment by pdelsante** [comment]
Hello, I still haven't had the time to look at the code, but it should be relatively easy to use the `WScriptShell.ExpandEnvironmentStrings()` to do exactly what you want to do. In the worst case, we'd have to add some more templates to each personality, but I think it's generally well worth the effort ;-)

Will look into this later today as soon as I get some time!

**Comment by tweemeterjop** [comment]
I was trying to get this to work but it seems the funcattrs are only used as setters and the attrs are only default values. Where should i put the code to set the values of attrs during init? Adding __init__() method to WScriptNetwork doesnt work.

**Comment by pdelsante** [comment]
Uhm, I am not sure what you mean.

When implementing the `WScriptShell.ExpandEnvironmentStrings()` function I only used values from `log.ThugOpts.Personality` (see: https://github.com/buffer/thug/blob/master/thug/ActiveX/modules/WScriptShell.py#L111-L114)

I would:

1. Implement one or more sections in the personality's JSON, containing some default values and some templates (see the `shellVariables` dict: https://github.com/buffer/thug/blob/master/thug/DOM/personalities/winxpie60.json#L21)
1. Implement a "getter" for values in that dict, see `getShellVariables` here: https://github.com/buffer/thug/blob/master/thug/DOM/Personality.py#L80)
1. Call the getter from your code (e.g. here: https://github.com/buffer/thug/pull/183/files#diff-b6ebdac1d462fcebf91f515dc61aa25dR14), possibly expanding any shell variables (e..g. `%name%`) or template variables (e.g. `{{name}}`) with any value you want.

Talking about `EnumerateNetworkDrives`, I would return a random list between 0 and, say, 4 items, with random (private) IP addresses or hostnames. The path portion could be completely random, as well, while the drive letter may well be somethin like `chr(random.choice(range(ord('E'), ord('Z'))))`.

As for `EnumPrinterConnections`, I would also include some default values that should almost always be there, like the Microsoft XPS Document Writer. For example, a VM with Office 2013 and a default configuration returns:

```
PortName                                                    Name
--------                                                    ----
nul:                                                        Send To OneNote 2013
XPSPort:                                                    Microsoft XPS Document Writer
SHRFAX:                                                     Fax
```
These values may well reside in the `Personality` json; we could also have a separate json config file with a set of common printer settings in terms of `PortName` and `Name`, like in the examples here: https://technet.microsoft.com/en-us/library/ff730984.aspx.

I'm not sure if I'm answering to your questions... :-)

**Comment by buffer** [comment]
@tweemeterjop I would really like to have this feature but can not help before Monday cause I will be traveling in the next hours. Please let me know if you need any kind of support. Thanks!

**Comment by tweemeterjop** [comment]
I couldn't find the time today, will try to make some changes tomorrow!

**Comment by tweemeterjop** [comment]
@pdelsante i know how to use the variables from the `Personality` but i've no idea where to implement the getter to populate[ these values](https://github.com/buffer/thug/pull/183/files#diff-c4d882faf0b0a8be581e9a2b3fbad852R1418) during init of the object. Maybe add some code to `__getattr__` in `ActiveX.py`? If the default value is empty then run the getter once?

**Comment by buffer** [comment]
If the issue is that, when setting the position value directly, the attribute value is not changed, the solution is to add as first line of the setPosition method the following line

self.__dict__['position'] = pos

Moreover the attribute is initialized as 0 through the 'attrs' dict.

Is this what you meant?

**Comment by tweemeterjop** [comment]
Thanks buffer, i fixed that.

Its about changing these default values from CLSID.py when the `WScriptNetwork` object is created.

`        'attrs'     : {
                        'UserDomain'            : 'User',
                        'ComputerName'          : 'User-PC',
                        'UserName'              : 'User',
                      },`

**Comment by buffer** [comment]
Let me know when you think the patching is complete and I will merge. I review the changes and really like them! Thanks!

**Comment by buffer** [comment]
Some ideas. You could use the same approach Pietro used with something like 

`''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(8)))''`

or you could just pick up a random entry at init time from a file like this

http://deron.meranda.us/data/census-dist-male-first.txt

and pick up a random name from the list at

**Comment by buffer** [comment]
Any update? I would really like to merge this PR so please let me know if I can help some way. Thanks!

**Comment by tweemeterjop** [comment]
Hi Angelo, i added some randomization for the list of network drives. Next i need to fix the UserName, UserDomain and ComputerName. I know how to get the values from the personality files but i have no clue where to implement the code to set or change the 'attrs' that are defined in CLSID.py. Creating a __init__ in my /modules/WScriptNetwork.py doesnt work, its not called on initialization of the object.

Can you point me to the right location where i should change or set the attrs defined in CLSID upon object initialization?

See:
https://github.com/buffer/thug/pull/183/commits/16f676ea981d5eb4876bd2dfd2b3061c9596b0a3#diff-c4d882faf0b0a8be581e9a2b3fbad852R1414

**Comment by buffer** [comment]
Thinking about a simple solution. We could try defining some properties for such purpose. For instance

```
@property
def UserDomain(self):
    do_randomization
    return randomized_user_domain
```

and then use it as an attr this way

```
'UserDomain'            : WScriptNetwork.UserDomain
```

Thoughts?

**Comment by buffer** [comment]
Great patch! Thank you very much!

**Pull request merged**
