### PR TITLE
Add runtime VirusTotal API key in ThugAPI and ThugOpts

### PR DESCRIPTION
**Pull request by pdelsante**
Allow users to specify a runtime key for VirusTotal APIs.

This may come handy when using a dockerized Thug version where editing the `virustotal.conf` file prior to each run is difficult.

I also created a `virustotal.default.conf` file that should always be there and that contains the default values for the `scanurl` and `reporturl` options; now, `virustotal.conf` can be used to store non-default values for those variables along with the primary API key. Also, `virustotal.conf` is not mandatory any more, since you could live with `virustotal.default.conf` plus a runtime API key value (e.g. the `--vt-apikey` command line option).

### CODE REVIEW

**Comment by buffer** [comment]
The patch is interesting but it is wrong. You are ignoring the default API key which is in virustotal.conf and if the user does not provide a key of his own you disable VT. This is not the way to go. I would suggest removing the new configuration file you added and if the user provides a runtime key then you just overwrite the default one. It is a simpler approach and works in all scenarios. Thanks.

**Comment by pdelsante** [comment]
Hi Angelo,

You are right that my patch is wrong, I did not keep into account that configparser (Python 3) and ConfigParser (Python 2) are not fully compatible. For example, ConfigParser uses `readfp()` instead of `read_file()`. I'll fix this as soon as possible.

However, the second configuration file is needed because there is no default value for `scanurl` and `reporturl`, so the runtime API key would only work if you set up your own `virustotal.conf` file *and* pass the runtime parameter, which is not always feasible. I mean, if you've got access to the `virustotal.conf` file you usually don't need to pass the API key as runtime as you'll be happy with the statically configured one. On the other hand, if you're using Docker, you don't have a `virustotal.conf` in place and that's where the runtime value comes handy; but if you don't have a default value for `reporturl` and `scanurl`, VirusTotal.py won't run even if you specify the key. Hence the need of a second config file. We could also put a default value for those parameters in VirusTotal.py itself, but I thought that a default config file would be a better approach.

I'll get back to you with the changes this evening.

**Comment by buffer** [comment]
The idea is quite simple. Just use the virustotal.conf as it is. If a VT API key is passed at runtime you just overwrite the apikey in opts. Why do you think this approach can't work?

**Comment by pdelsante** [comment]
Well, because `virustotal.conf` isn't there by default, so you have to create it by hand anyway and this is what I would like to avoid. Running the Docker instance in "one-shot mode" would require you to:
1. start the Docker container
2. copy `virustotal.conf.example` to `virustotal.conf`
3. run Thug passing the API key as a runtime option

But, of course, if you can do 2., you can also put the API key there and there's no need for a command line option or anything the like. On the other hand, if you accept my approach, the whole thing will become:
1. run thug.py under docker passing the runtime API key

My idea is that of minimizing the number of configuration files you have to edit by hand, by accepting runtime options. I thought that using a `virustotal.default.conf` file was also appropriate because the API entry points do not change often and most people should be fine with their default value (unless they're using some sort of proxy).

Another option would be to also allow the `scanurl` and `reporturl` parameters to be set at runtime, but I don't think there would me many use cases for this. What's your opinion about that?

**Comment by buffer** [comment]
https://github.com/buffer/thug/commit/f336577d6a2709a9a63c1aff47c2a7786bfc4cf3

No excuses now ;)

**Comment by pdelsante** [comment]
Sure, Boss! I shall obey to your command! :dart: :+1:

**Comment by pdelsante** [comment]
Should be ready now!

Cheers,
P.

**Pull request merged**
